name: Release osu!fm

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install wine
        run: |
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo dpkg --add-architecture i386 
          sudo apt update
          sudo apt install --install-recommends winehq-stable

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --immutable

      - name: Build & Release Electron app
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/*.AppImage
            dist/*.exe
